// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD_nmPTqPqsff3aVQoq1z_wB8nQAJDuUzs',
    appId: '1:25628425137:web:08434b00cb49e2a0a99b90',
    messagingSenderId: '25628425137',
    projectId: 'chat-app-68f49',
    authDomain: 'chat-app-68f49.firebaseapp.com',
    storageBucket: 'chat-app-68f49.appspot.com',
    measurementId: 'G-XWG14GJFCN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDTDPOh44jFPz4_owGSVjavW2BurbY2Ib0',
    appId: '1:25628425137:android:5695cc6d70b55278a99b90',
    messagingSenderId: '25628425137',
    projectId: 'chat-app-68f49',
    storageBucket: 'chat-app-68f49.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDxAM3gv1fdIWv1FT4_yBORr3oJuHzjkiU',
    appId: '1:25628425137:ios:5d7178ae6aa51fbfa99b90',
    messagingSenderId: '25628425137',
    projectId: 'chat-app-68f49',
    storageBucket: 'chat-app-68f49.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDxAM3gv1fdIWv1FT4_yBORr3oJuHzjkiU',
    appId: '1:25628425137:ios:5d7178ae6aa51fbfa99b90',
    messagingSenderId: '25628425137',
    projectId: 'chat-app-68f49',
    storageBucket: 'chat-app-68f49.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD_nmPTqPqsff3aVQoq1z_wB8nQAJDuUzs',
    appId: '1:25628425137:web:a63372914d432ba8a99b90',
    messagingSenderId: '25628425137',
    projectId: 'chat-app-68f49',
    authDomain: 'chat-app-68f49.firebaseapp.com',
    storageBucket: 'chat-app-68f49.appspot.com',
    measurementId: 'G-F49KQ1HZ9W',
  );
}
